# Generated by Django 4.2.1 on 2023-07-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=254)),
                ('phone', models.IntegerField(default=0)),
                ('roll', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('college', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
