# Generated by Django 4.2.1 on 2023-07-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tedapp', '0002_rename_account_useraccount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='roll',
            new_name='refferal',
        ),
    ]
